#!/usr/bin/env node

const fs = require('fs');
const RE_RELEASE_LINK = /\[latest build from master\].*/;

const new_release = process.argv[2];

let readme = fs.readFileSync('README.md').toString();
readme = readme.replace(RE_RELEASE_LINK,
  `[latest build from master]` +
  `(https://github.com/ayazhafiz/gradec/releases/tag/${new_release})`);

fs.writeFileSync('README.md', readme);
